app/base/urls.py
from django.urls import path

from app.base.views import Home

#--Importamos las view de la aplicación base
from .views import Home, Acercade

from django.contrib.auth import views as auth_views

#--Generamos las urls de la aplicación base 

urlpatterns = [
    
    # Url de vistas basadas en clase
    path('',Home.as_view(), name='index'),
    path('acercade/', Acercade.as_view(), name='acercade'),

    path('login/',auth_views.LoginView.as_view(template_name='base/login.html'),name='login'),
	path('logout/',auth_views.LogoutView.as_view(template_name='base/login.html'),name='logout'),


    #Url de vistas en funciones
    #path('',Home, name='index'),
    #path('acercade/', Acercade, name='acercade'),
   
]

app/proveedor/urls.py
from django.urls import path

from .views import NuevoProveedor, ListadoProveedor,DetalleProveedor, BuscarProveedor, EditarProveedor, EliminarProveedor

urlpatterns = [
    # Vistas Basadas en clase
    path('nuevoproveedor/', NuevoProveedor.as_view(),name='nuevoproveedor'),
    path('listadoproveedor/',ListadoProveedor.as_view(),name='listadoproveedor'),
    path('detalleproveedor/<int:pk>',DetalleProveedor.as_view(),name='detalleproveedor'),
    path('buscarproveedor/',BuscarProveedor.as_view(),name='buscarproveedor'),
    path('editarproveedor/<int:pk>',EditarProveedor.as_view(),name='editarproveedor'),
    path('eliminarproveedor/<int:pk>',EliminarProveedor.as_view(),name='eliminarproveedor')


    
    #Vistas Basadas en Función
    #path('nuevoproveedor/', NuevoProveedor,name='nuevoproveedor'),
    #path('listadoproveedor/',ListadoProveedor,name='listadoproveedor')
    
]

tienda/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include(('app.base.urls','base'),namespace='base')),
    path('producto/',include(('app.producto.urls','producto'),namespace='producto')),
    path('cliente/',include(('app.cliente.urls','cliente'),namespace='cliente')),
    path('vendedor/',include(('app.vendedor.urls','vendedor'),namespace='vendedor')),
    path('proveedor/',include(('app.proveedor.urls','proveedor'),namespace='proveedor')),
    path('usuario/',include(('app.usuario.urls','usuario'),namespace='usuario'))
]

app/proveedor/models.py
from django.db import models

from app.cliente.models import Pais
# Create your models here.
class Proveedor(models.Model):
    codigo_proveedor = models.CharField(max_length=50, verbose_name='Código')
    nombre_proveedor = models.CharField(max_length=50, verbose_name='Nombre')
    domicilio_proveedor = models.CharField(max_length=150, verbose_name='Domicilio')
    telfijo_proveedor = models.CharField(max_length=10, verbose_name='Teléfono',null=True, blank=True)
    movil_proveedor = models.CharField(max_length=10, verbose_name='Celular',null=True, blank=True)
    email_proveedor = models.EmailField(verbose_name='Correo Electrónico',null=True, blank=True)
    zipcode_proveedor = models.CharField(max_length=10, verbose_name='Código Postal') 
    id_pais = models.ForeignKey(Pais, on_delete=models.CASCADE,verbose_name='Pais')
   
    

    def __str__(self):
        return 'Nombre Proveedor: {}'.format(self.nombre_proveedor)
    
   
    class Meta:
        verbose_name_plural = 'Proveedores'
        ordering = ['nombre_proveedor'] 

app/proveedor/forms.py
from django import forms
from .models import Proveedor

class ProveedorForm(forms.ModelForm):

    class Meta:
        model = Proveedor
        fields = ('__all__')

app/proveedor/views.py
from django.shortcuts import render, redirect

from django.urls import reverse_lazy
from django.views import generic

from django.contrib.auth.mixins import LoginRequiredMixin

from .models import Proveedor
from .forms import ProveedorForm

# Vistas Basadas en Clase
class NuevoProveedor(LoginRequiredMixin,generic.CreateView):
    model = Proveedor
    template_name = 'proveedor/nuevo_proveedor.html'
    context_object_name = 'form'
    form_class = ProveedorForm
    success_url = reverse_lazy('proveedor:listadoproveedor')
    login_url = 'base:login'


class ListadoProveedor(LoginRequiredMixin,generic.ListView):
    model = Proveedor
    template_name = 'proveedor/listado_proveedor.html'
    context_object_name = 'provee'
    login_url = 'base:login'


class DetalleProveedor(LoginRequiredMixin,generic.DetailView):
    model = Proveedor
    template_name = 'proveedor/detalle_proveedor.html'
    context_object_name = 'provee'
    login_url = 'base:login'


class BuscarProveedor(LoginRequiredMixin,generic.ListView):
    template_name = 'proveedor/buscar_proveedor.html'
    context_object_name = 'provee'
    login_url = 'base:login'
    
    def get_queryset(self):
        palabra_clave = self.request.GET.get("kword")
        if not palabra_clave:
            palabra_clave = "None"
        return Proveedor.objects.filter(nombre_proveedor__icontains=palabra_clave)


class EditarProveedor(LoginRequiredMixin,generic.UpdateView):
    model = Proveedor
    template_name = 'proveedor/editar_proveedor.html'
    context_object_name = 'obj'
    form_class = ProveedorForm
    success_url = reverse_lazy('proveedor:listadoproveedor')
    login_url = 'base:login'



class EliminarProveedor(LoginRequiredMixin,generic.DeleteView):
    model = Proveedor
    template_name = 'proveedor/eliminar_proveedor.html'
    success_url = reverse_lazy('proveedor:listadoproveedor')
    login_url = 'base:login'


"""
# Vista de Nuevo Proveedor.
def NuevoProveedor(request):

    if request.method == 'POST':
        formulario_proveedor= ProveedorForm(request.POST)
        if formulario_proveedor.is_valid():
            formulario_proveedor.save()
            return redirect('proveedor:listadoproveedor')
    else:
        formulario_proveedor = ProveedorForm()
    
    return render(request, 'proveedor/nuevo_proveedor.html',{'form':formulario_proveedor})

    



# Vista Listado Proveedor
def ListadoProveedor(request):
    proveedor = Proveedor.objects.all() # Trae todos los registros de la tabla proveedor
    return render(request, 'proveedor/listado_proveedor.html',{'provee':proveedor})
"""

app/proveedor/templates/proveedor/buscar_proveedor.html
{% extends 'base/base.html' %}
{% load widget_tweaks %}

{%block titulo-miga%}
<div class="row">
    <div class="col-12">
        <div class="page-title-box">
            <h4 class="page-title">Página de Proveedores</h4>
            <div>

                <ol class="breadcrumb m-0">
                    <li class="breadcrumb-item"><a href="{% url 'base:index' %}">Home</a></li>
                    <li class="breadcrumb-item active">Buscar Proveedor</li>
                </ol>

            </div>
        </div>
    </div>
</div>
{% endblock%}

{% block contenido %}


<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body">
                <h4 class="header-title">Formulario de Búsqueda de Proveedores</h4>
                <br>
                <form method="GET">
                    {% csrf_token %}

                    <div class="mb-3">
                        <label for="example-input-normal" class="form-label">Buscar Proveedor (Nombre)</label>
                        <input type="text" id="kword" name="kword" class="form-control">
                    </div>

                    <button type="submit" class="btn btn-primary waves-effect waves-light">Buscar Proveedor</button>

                </form>

            </div>
        </div>
    </div>

</div>

<hr>
<div class="row">
    <div class="col-lg-12">
        <div class="card">
            <div class="card-body">
                <h4 class="header-title">Listado de Proveedores</h4>
                <hr>
                {% if provee %}
                <div class="table-responsive">
                    <table class="table table-dark mb-0">
                        <thead>
                            <tr>
                                <th>Nombre</th>
                                <th>Código</th>
                                <th>Domicilio</th>
                                <th>Código Postal</th>
                                <th>País</th>
                                <th>Acciones</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for i in provee %}
                            <tr>
                                <th>{{i.nombre_proveedor}}</th>
                                <td>{{i.codigo_proveedor}}</td>
                                <td>{{i.domicilio_proveedor}}</td>
                                <td>{{i.zipcode_proveedor}}</td>
                                <td>{{i.id_pais}}</td>
                                <td>
                                    <a href="{%url 'proveedor:detalleproveedor' i.id%}" class="btn btn-soft-info btn-rounded waves-effect waves-light">Más Info</a>
                                   
                                </td>
                                
                                
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
                {% else %}
                <div class="alert alert-warning" role="alert">
                    <i class="mdi mdi-alert-outline me-2"></i> ATENCIÓN: <strong>No se encuentran coincidencias</strong> 
                </div>
                {% endif %}
            </div>
        </div> <!-- end card -->
    </div> <!-- end col -->
</div>





{% endblock %}

app/proveedor/templates/proveedor/detalle_proveedor.html
{% extends 'base/base.html' %}


{%block titulo-miga%}
<div class="row">
    <div class="col-12">
        <div class="page-title-box">
            <h4 class="page-title">Página de Proveedores</h4>
            <div>

                <ol class="breadcrumb m-0">
                    <li class="breadcrumb-item"><a href="{% url 'base:index' %}">Home</a></li>
                    <li class="breadcrumb-item active">Detalle del proveedor</li>
                </ol>

            </div>
        </div>
    </div>
</div>
{% endblock%}

{% block contenido %}


<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body">
                <h4 class="header-title">Detalles del Proveedor</h4>
               <hr>

                <form>
                    <div class="row">
                        <div class="mb-3 col-md-4">
                            <label for="inputEmail4" class="form-label">Nombre</label>
                            <input type="text" class="form-control" value="{{provee.nombre_proveedor}}" >
                        </div>
                        <div class="mb-3 col-md-4">
                            <label for="inputPassword4" class="form-label">Código</label>
                            <input type="text" class="form-control" value="{{provee.codigo_proveedor}}" >
                        </div>
                        <div class="mb-3 col-md-4">
                            <label for="inputState" class="form-label">Email</label>
                            <input type="text" class="form-control" value="{{provee.email_proveedor}}">
                        </div>
                    </div>

                    <div class="mb-3">
                        <label for="inputAddress" class="form-label">Domicilio</label>
                        <input type="text" class="form-control" value="{{provee.domicilio_proveedor}}">
                       
                    </div>

                    <div class="row">
                        <div class="mb-3 col-md-4">
                            <label for="inputCity" class="form-label">Tel Fijo</label>
                            <input type="text" class="form-control" value="{{provee.telfijo_proveedor}}">
                        </div>
                        <div class="mb-3 col-md-4">
                            <label for="inputState" class="form-label">Tel Movil</label>
                            <input type="text" class="form-control" value="{{provee.movil_proveedor}}">
                        </div>
                        <div class="mb-3 col-md-4">
                            <label for="inputCity" class="form-label">Código Postal</label>
                            <input type="text" class="form-control" value="{{provee.zipcode_proveedor}}">
                        </div>
                       
                        
                    </div>
                    <div class="row">
                       
                        <div class="mb-3">
                            <label for="inputState" class="form-label">País</label>
                            <input type="text" class="form-control" value="{{provee.id_pais}}">
                        </div>
                       
                        
                    </div>

                   
                </form>
                <button onclick="history.go(-1)" class="btn btn-success waves-effect waves-light">Regresar</button>
            </div> <!-- end card-body -->
        </div> <!-- end card-->
    </div> <!-- end col -->
</div>
{% endblock %}

app/proveedor/templates/proveedor/editar_proveedor.html
{% extends 'base/base.html' %}
{% load widget_tweaks %}

{%block titulo-miga%}
<div class="row">
    <div class="col-12">
        <div class="page-title-box">
            <h4 class="page-title">Página de Proveedores</h4>
            <div>

                <ol class="breadcrumb m-0">
                    <li class="breadcrumb-item"><a href="{% url 'base:index' %}">Home</a></li>
                    <li class="breadcrumb-item active">Editar Datos Proveedores</li>
                </ol>

            </div>
        </div>
    </div>
</div>
{% endblock%}

{% block contenido %}


<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body">
                <h4 class="header-title">Formulario de Edición de Proveedores</h4>
               <hr>
                <form method="POST">
                    {% csrf_token %}
                    <div class="row">
                        <div class="col-md-6 mb-3">
                            <label for="inputEmail4" class="form-label">Código</label>
                            {% render_field form.codigo_proveedor class="form-control" %}
                        </div>
                        <div class="col-md-6 mb-3">
                            <label for="inputPassword4" class="form-label">Nombre</label>
                            {% render_field form.nombre_proveedor class="form-control" %}
                        </div>
                        <div class="mb-3">
                            <label for="inputAddress" class="form-label">Domicilio</label>
                            {% render_field form.domicilio_proveedor class="form-control" %}
                        </div>
                    </div>

                    

                    <div class="row">
                        <div class="mb-3 col-md-2">
                            <label for="inputCity" class="form-label">Tel Fijo</label>
                            {% render_field form.telfijo_proveedor class="form-control" %}
                        </div>
                        <div class="mb-3 col-md-4">
                            <label for="inputState" class="form-label">Tel Movil</label>
                            {% render_field form.movil_proveedor class="form-control" %}
                        </div>
                        <div class="mb-3 col-md-6">
                            <label for="inputZip" class="form-label">Email</label>
                            {% render_field form.email_proveedor class="form-control" %}
                        </div>
                        
                    </div>

                    <div class="row">
                        <div class="mb-3 col-md-6">
                            <label for="inputCity" class="form-label">Código Postal</label>
                            {% render_field form.zipcode_proveedor class="form-control" %}
                        </div>
                        <div class="mb-3 col-md-6">
                            <label for="inputState" class="form-label">País</label>
                            {% render_field form.id_pais class="form-control" %}
                        </div>
                       
                        
                    </div>
                    <button type="submit" class="btn btn-primary waves-effect waves-light">Editar Registro</button>
                    <button onClick="history.go(-1);" class="btn btn-success waves-effect waves-light">Cancelar</button>
                </form>

            </div> 
    </div> 
</div>
</div>
{% endblock %}

app/proveedor/templates/proveedor/eliminar_proveedor.html
{% extends 'base/base.html' %}
{% load widget_tweaks %}

{%block titulo-miga%}
<div class="row">
    <div class="col-12">
        <div class="page-title-box">
            <h4 class="page-title">Página de Proveedores</h4>
            <div>

                <ol class="breadcrumb m-0">
                    <li class="breadcrumb-item"><a href="{% url 'base:index' %}">Home</a></li>
                    <li class="breadcrumb-item active">Eliminar Proveedores</li>
                </ol>

            </div>
        </div>
    </div>
</div>
{% endblock%}

{% block contenido %}


<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body">
                <h4 class="header-title">Eliminar Proveedores</h4>
               <hr>
               <div class="alert alert-danger bg-danger text-white border-0" role="alert">
                Esta seguro de  <strong>ELIMINAR</strong> este proveedore...???
                <br>
                <br>
                Código / Nombre Proveedor: <strong> {{object.codigo_proveedor}}, {{object.nombre_proveedor}}</strong>
                <br>
                <br>
                Email: <strong>{{object.email_proveedor}}</strong> 
                </div>
                <hr>
                <form method="POST">
                    {% csrf_token %}
                   
                    <button type="submit" class="btn btn-warning waves-effect waves-light">Eliminar Proveedor</button>
                    <button onClick="history.go(-1);" class="btn btn-success waves-effect waves-light">Cancelar</button>
                </form>

            </div> 
    </div> 
</div>
</div>
{% endblock %}

app/proveedor/templates/proveedor/listado_proveedor.html
{% extends 'base/base.html' %}

{%block titulo-miga%}
<div class="row">
    <div class="col-12">
        <div class="page-title-box">
            <h4 class="page-title">Página de Proveedores</h4>
            <div>

                <ol class="breadcrumb m-0">
                    <li class="breadcrumb-item"><a href="{% url 'base:index' %}">Home</a></li>
                    <li class="breadcrumb-item active">Listado de Proveedores</li>
                </ol>

            </div>
        </div>
    </div>
</div>
{% endblock%}

{% block contenido %}
<div class="row">
    <div class="col-lg-12">
        <div class="card">
            <div class="card-body">
                <h4 class="header-title">Listado de Proveedores</h4>
                

                <div class="table-responsive">
                    <table class="table table-dark mb-0">
                        <thead>
                            <tr>
                                <th>Nombre</th>
                                <th>Código</th>
                                <th>Domicilio</th>
                                <th>Código Postal</th>
                                <th>País</th>
                                <th>Acciones</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for i in provee %}
                            <tr>
                                <th>{{i.nombre_proveedor}}</th>
                                <td>{{i.codigo_proveedor}}</td>
                                <td>{{i.domicilio_proveedor}}</td>
                                <td>{{i.zipcode_proveedor}}</td>
                                <td>{{i.id_pais}}</td>
                                <td>
                                    <a href="{%url 'proveedor:detalleproveedor' i.id%}" class="btn btn-soft-info btn-rounded waves-effect waves-light">Más Info</a>
                                    <a href="{%url 'proveedor:editarproveedor' i.id%}" class="btn btn-soft-warning btn-rounded waves-effect waves-light">Editar</a>
                                    <a href="{%url 'proveedor:eliminarproveedor' i.id%}" class="btn btn-soft-danger btn-rounded waves-effect waves-light">Eliminar</a>
                                </td>
                                
                                
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div> <!-- end card -->
    </div> <!-- end col -->
</div>
{% endblock %}

app/proveedor/templates/proveedor/nuevo_proveedor.html
{% extends 'base/base.html' %}
{% load widget_tweaks %}

{%block titulo-miga%}
<div class="row">
    <div class="col-12">
        <div class="page-title-box">
            <h4 class="page-title">Pagina de Proveedores</h4>
            <div>

                <ol class="breadcrumb m-0">
                    <li class="breadcrumb-item"><a href="{% url 'base:index' %}">Home</a></li>
                    <li class="breadcrumb-item active">Cargar Nuevo Proveedor</li>
                </ol>

            </div>
        </div>
    </div>
</div>
{% endblock%}

{% block contenido %}
<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body">
                <h4 class="header-title">Formulario de Carga de Proveedores</h4>
               <hr>
                <form method="POST">
                    {% csrf_token %}
                    <div class="row">
                        <div class="col-md-6 mb-3">
                            <label for="inputEmail4" class="form-label">Código</label>
                            {% render_field form.codigo_proveedor class="form-control" %}
                        </div>
                        <div class="col-md-6 mb-3">
                            <label for="inputPassword4" class="form-label">Nombre</label>
                            {% render_field form.nombre_proveedor class="form-control" %}
                        </div>
                        <div class="mb-3">
                            <label for="inputAddress" class="form-label">Domicilio</label>
                            {% render_field form.domicilio_proveedor class="form-control" %}
                        </div>
                    </div>

                    

                    <div class="row">
                        <div class="mb-3 col-md-2">
                            <label for="inputCity" class="form-label">Tel Fijo</label>
                            {% render_field form.telfijo_proveedor class="form-control" %}
                        </div>
                        <div class="mb-3 col-md-4">
                            <label for="inputState" class="form-label">Tel Movil</label>
                            {% render_field form.movil_proveedor class="form-control" %}
                        </div>
                        <div class="mb-3 col-md-6">
                            <label for="inputZip" class="form-label">Email</label>
                            {% render_field form.email_proveedor class="form-control" %}
                        </div>
                        
                    </div>

                    <div class="row">
                        <div class="mb-3 col-md-6">
                            <label for="inputCity" class="form-label">Código Postal</label>
                            {% render_field form.zipcode_proveedor class="form-control" %}
                        </div>
                        <div class="mb-3 col-md-6">
                            <label for="inputState" class="form-label">País</label>
                            {% render_field form.id_pais class="form-control" %}
                        </div>
                       
                        
                    </div>
                   
                    <button type="submit" class="btn btn-primary waves-effect waves-light">Cargar Registro</button>

                </form>

            </div> 
    </div> 
</div>
</div>
{% endblock %}