app/base/urls.py
from django.urls import path

from app.base.views import Home

#--Importamos las view de la aplicación base
from .views import Home, Acercade

from django.contrib.auth import views as auth_views

#--Generamos las urls de la aplicación base 

urlpatterns = [
    
    # Url de vistas basadas en clase
    path('',Home.as_view(), name='index'),
    path('acercade/', Acercade.as_view(), name='acercade'),

    path('login/',auth_views.LoginView.as_view(template_name='base/login.html'),name='login'),
	path('logout/',auth_views.LogoutView.as_view(template_name='base/login.html'),name='logout'),


    #Url de vistas en funciones
    #path('',Home, name='index'),
    #path('acercade/', Acercade, name='acercade'),
   
]

app/cliente/urls.py
from django.urls import path

from .views import NuevoCliente, ListadoCliente, DetalleCliente, BuscarCliente,EditarCliente,EliminarCliente

urlpatterns = [
    path('nuevocliente/', NuevoCliente.as_view(), name='nuevocliente'),
    path('listadocliente/', ListadoCliente.as_view(), name='listadocliente'),
    path('detallecliente/<int:pk>',DetalleCliente.as_view(),name='detallecliente'),
    path('buscarcliente/',BuscarCliente.as_view(), name='buscarcliente'),
    path('editarcliente/<int:pk>',EditarCliente.as_view(),name='editarcliente'),
    path('eliminarcliente/<int:pk>',EliminarCliente.as_view(),name='eliminarcliente')

    

    
]

tienda/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include(('app.base.urls','base'),namespace='base')),
    path('producto/',include(('app.producto.urls','producto'),namespace='producto')),
    path('cliente/',include(('app.cliente.urls','cliente'),namespace='cliente')),
    path('vendedor/',include(('app.vendedor.urls','vendedor'),namespace='vendedor')),
    path('proveedor/',include(('app.proveedor.urls','proveedor'),namespace='proveedor')),
    path('usuario/',include(('app.usuario.urls','usuario'),namespace='usuario'))
]

app/cliente/models.py
from django.db import models

# Create your models here.
class Pais(models.Model):

    pais = models.CharField(max_length=150, verbose_name='Pais',unique=True,
                blank=False, null=False)
    

    def __str__(self):
        return '{}'.format(self.pais)
    
        
    class Meta:
        verbose_name_plural = "Paises"
        ordering = ['pais']




class Cliente(models.Model):
    nombre_cliente = models.CharField(max_length=50, verbose_name='Nombre')
    apellido_cliente = models.CharField(max_length=50, verbose_name='Apellido')
    dni_cliente = models.CharField(max_length=10, verbose_name='DNI') 
    domicilio_cliente = models.CharField(max_length=150, verbose_name='Domicilio')
    telfijo_cliente = models.CharField(max_length=10, verbose_name='Teléfono',null=True, blank=True)
    movil_cliente = models.CharField(max_length=10, verbose_name='Celular',null=True, blank=True)
    email_cliente = models.EmailField(verbose_name='Correo Electrónico',null=True, blank=True)
    zipcode_cliente = models.CharField(max_length=10, verbose_name='Código Postal') 
    id_pais = models.ForeignKey(Pais, on_delete=models.CASCADE,verbose_name='Pais')
   
    

    def __str__(self):
        return 'Apellido y Nombre: {}, {}'.format(self.apellido_cliente,self.nombre_cliente)
    
   
    class Meta:
        verbose_name_plural = 'Clientes'
        ordering = ['apellido_cliente'] 

app/cliente/forms.py
from django import forms
from django.forms import fields
from .models import Cliente

class ClienteForm(forms.ModelForm):

    class Meta:
        model = Cliente
        fields = ('__all__')
    
    
   

app/cliente/views.py
from django.shortcuts import redirect, render
from django.urls import reverse_lazy
from django.views import generic

from django.contrib.auth.mixins import LoginRequiredMixin

from app.cliente.models import Cliente
from .forms import ClienteForm

# Vistas Basadas en Clase

class NuevoCliente(LoginRequiredMixin,generic.CreateView):
    model = Cliente
    template_name = 'cliente/nuevo_cliente.html'
    context_object_name = 'form'
    form_class = ClienteForm
    success_url = reverse_lazy('cliente:listadocliente')
    login_url = 'base:login'


class ListadoCliente(LoginRequiredMixin,generic.ListView):
    model = Cliente
    template_name = 'cliente/listado_cliente.html'
    context_object_name = 'cli'
    login_url = 'base:login'


class DetalleCliente(LoginRequiredMixin,generic.DetailView):
    model = Cliente
    template_name = 'cliente/detalle_cliente.html'
    context_object_name = 'cli'
    login_url = 'base:login'


class BuscarCliente(LoginRequiredMixin,generic.ListView):
    template_name = 'cliente/buscar_cliente.html'
    context_object_name = 'cli'
    login_url = 'base:login'
    
    def get_queryset(self):
        palabra_clave = self.request.GET.get("kword")
        if not palabra_clave:
            palabra_clave = "None"
        return Cliente.objects.filter(apellido_cliente__icontains=palabra_clave)



class EditarCliente(LoginRequiredMixin,generic.UpdateView):
    model = Cliente
    template_name = 'cliente/editar_cliente.html'
    context_object_name = 'obj'
    form_class = ClienteForm
    success_url = reverse_lazy('cliente:listadocliente')
    login_url = 'base:login'



class EliminarCliente(LoginRequiredMixin,generic.DeleteView):
    model = Cliente
    template_name = 'cliente/eliminar_cliente.html'
    success_url = reverse_lazy('cliente:listadocliente')
    login_url = 'base:login'



"""
VISTAS BASADAS EN FUNCIONES

# Vista de Nuevo Cliente.
def NuevoCliente(request):

    if request.method == 'POST':
        formulario_cliente= ClienteForm(request.POST)
        if formulario_cliente.is_valid():
            formulario_cliente.save()
            return redirect('cliente:listadocliente')
    else:
        formulario_cliente = ClienteForm()
    
    return render(request, 'cliente/nuevo_cliente.html',{'form':formulario_cliente})

  


# Vista Listado Cliente
def ListadoCliente(request):
    cliente = Cliente.objects.all() # Trae todos los registros de la tabla clientes
    return render(request, 'cliente/listado_cliente.html',{'cli':cliente})
"""

app/cliente/templates/cliente/buscar_cliente.html
{% extends 'base/base.html' %}
{% load widget_tweaks %}

{%block titulo-miga%}
<div class="row">
    <div class="col-12">
        <div class="page-title-box">
            <h4 class="page-title">Página de Clientes</h4>
            <div>

                <ol class="breadcrumb m-0">
                    <li class="breadcrumb-item"><a href="{% url 'base:index' %}">Home</a></li>
                    <li class="breadcrumb-item active">Buscar Cliente</li>
                </ol>

            </div>
        </div>
    </div>
</div>
{% endblock%}

{% block contenido %}


<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body">
                <h4 class="header-title">Formulario de Búsqueda de Cliente</h4>
                <br>
                <form method="GET">
                    {% csrf_token %}

                    <div class="mb-3">
                        <label for="example-input-normal" class="form-label">Buscar Cliente (Apellido)</label>
                        <input type="text" id="kword" name="kword" class="form-control">
                    </div>

                    <button type="submit" class="btn btn-primary waves-effect waves-light">Buscar Cliente</button>

                </form>

            </div>
        </div>
    </div>

</div>

<hr>


<div class="row">
    <div class="col-lg-12">
        <div class="card">
            <div class="card-body">
                <h4 class="header-title">Listado de Clientes</h4>
                <hr>
                {% if cli %}
                <div class="table-responsive">
                    <table class="table table-dark mb-0">
                        <thead>
                            <tr>
                                <th>Apellido</th>
                                <th>Nombre</th>
                                <th>DNI</th>
                                <th>Domicilio</th>
                                <th>Acciones</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for i in cli %}
                            <tr>
                                <th>{{i.apellido_cliente}}</th>
                                <td>{{i.nombre_cliente}}</td>
                                <td>{{i.dni_cliente}}</td>
                                <td>{{i.domicilio_cliente}}</td>
                                <td><a href="{% url 'cliente:detallecliente' i.id %}"" class="btn btn-soft-info btn-rounded waves-effect waves-light">Más Info</a>
                               
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
                {% else %}
                <div class="alert alert-warning" role="alert">
                    <i class="mdi mdi-alert-outline me-2"></i> ATENCIÓN: <strong>No se encuentran coincidencias</strong> 
                </div>
                {% endif %}
                
            </div>
        </div> <!-- end card -->
    </div> <!-- end col -->
</div>

{% endblock %}

app/cliente/templates/cliente/detalle_cliente.html
{% extends 'base/base.html' %}


{%block titulo-miga%}
<div class="row">
    <div class="col-12">
        <div class="page-title-box">
            <h4 class="page-title">Página de Clientes</h4>
            <div>

                <ol class="breadcrumb m-0">
                    <li class="breadcrumb-item"><a href="{% url 'base:index' %}">Home</a></li>
                    <li class="breadcrumb-item active">Detalle del Cliente</li>
                </ol>

            </div>
        </div>
    </div>
</div>
{% endblock%}

{% block contenido %}


<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body">
                <h4 class="header-title">Detalles del Cliente</h4>
               <hr>

                <form>
                    <div class="row">
                        <div class="col-md-6 mb-3">
                            <label for="inputEmail4" class="form-label">Apellido</label>
                            <input type="text" class="form-control" value="{{cli.apellido_cliente}}" placeholder="Email">
                        </div>
                        <div class="col-md-6 mb-3">
                            <label for="inputPassword4" class="form-label">Nombre</label>
                            <input type="text" class="form-control" value="{{cli.nombre_cliente}}" placeholder="Password">
                        </div>
                    </div>

                    <div class="mb-3">
                        <label for="inputAddress" class="form-label">Domicilio</label>
                        <input type="text" class="form-control" value="{{cli.domicilio_cliente}}" placeholder="1234 Main St">
                    </div>

                    <div class="row">
                        <div class="mb-3 col-md-6">
                            <label for="inputCity" class="form-label">DNI</label>
                            <input type="text" class="form-control" value="{{cli.dni_cliente}}">
                        </div>
                        <div class="mb-3 col-md-4">
                            <label for="inputState" class="form-label">Tel. Fijo</label>
                            <input type="text" class="form-control" value="{{cli.telfijo_cliente}}">
                        </div>
                        <div class="mb-3 col-md-2">
                            <label for="inputZip" class="form-label">Tel Movil</label>
                            <input type="text" class="form-control" value="{{cli.movil_cliente}}">
                        </div>
                    </div>

                    <div class="row">
                        <div class="mb-3 col-md-6">
                            <label for="inputCity" class="form-label">Email</label>
                            <input type="text" class="form-control" value="{{cli.email_cliente}}">
                        </div>
                        <div class="mb-3 col-md-4">
                            <label for="inputState" class="form-label">Código Postal</label>
                            <input type="text" class="form-control" value="{{cli.zipcode_cliente}}">
                        </div>
                        <div class="mb-3 col-md-2">
                            <label for="inputZip" class="form-label">País</label>
                            <input type="text" class="form-control" value="{{cli.id_pais}}">
                        </div>
                    </div>
                </form>
                <button onClick="history.go(-1);" class="btn btn-success waves-effect waves-light">Regresar</button>
            </div> <!-- end card-body -->
        </div> <!-- end card-->
    </div> <!-- end col -->
</div>
{% endblock %}

app/cliente/templates/cliente/editar_cliente.html
{% extends 'base/base.html' %}
{% load widget_tweaks %}

{%block titulo-miga%}
<div class="row">
    <div class="col-12">
        <div class="page-title-box">
            <h4 class="page-title">Página de Clientes</h4>
            <div>

                <ol class="breadcrumb m-0">
                    <li class="breadcrumb-item"><a href="{% url 'base:index' %}">Home</a></li>
                    <li class="breadcrumb-item active">Editar Datos Cliente</li>
                </ol>

            </div>
        </div>
    </div>
</div>
{% endblock%}

{% block contenido %}


<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body">
                <h4 class="header-title">Formulario de Edición de Cliente</h4>
               <hr>
                <form method="POST">
                    {% csrf_token %}
                    <div class="row">
                        <div class="col-md-6 mb-3">
                            <label for="inputEmail4" class="form-label">Apellido</label>
                            {% render_field form.apellido_cliente class="form-control" %}
                        </div>
                        <div class="col-md-6 mb-3">
                            <label for="inputPassword4" class="form-label">Nombre</label>
                            {% render_field form.nombre_cliente class="form-control" %}
                        </div>
                    </div>

                    <div class="mb-3">
                        <label for="inputAddress" class="form-label">Domicilio</label>
                        {% render_field form.domicilio_cliente class="form-control" %}
                    </div>

                    <div class="row">
                        <div class="mb-3 col-md-6">
                            <label for="inputCity" class="form-label">DNI</label>
                            {% render_field form.dni_cliente class="form-control" %}
                        </div>
                        <div class="mb-3 col-md-4">
                            <label for="inputState" class="form-label">Tel. Fijo</label>
                            {% render_field form.telfijo_cliente class="form-control" %}
                        </div>
                        <div class="mb-3 col-md-2">
                            <label for="inputZip" class="form-label">Tel. Móvil</label>
                            {% render_field form.movil_cliente class="form-control" %}
                        </div>
                    </div>
                    <div class="row">
                        <div class="mb-3 col-md-6">
                            <label for="inputCity" class="form-label">Email</label>
                            {% render_field form.email_cliente class="form-control" %}
                        </div>
                        <div class="mb-3 col-md-4">
                            <label for="inputState" class="form-label">Código Postal</label>
                            {% render_field form.zipcode_cliente class="form-control" %}
                        </div>
                        <div class="mb-3 col-md-2">
                            <label for="inputZip" class="form-label">País</label>
                            {% render_field form.id_pais class="form-control" %}
                        </div>
                    </div>
                    <button type="submit" class="btn btn-primary waves-effect waves-light">Editar Registro</button>
                    <button onClick="history.go(-1);" class="btn btn-success waves-effect waves-light">Cancelar</button>
                </form>

            </div> 
    </div> 
</div>
</div>
{% endblock %}

app/cliente/templates/cliente/eliminar_cliente.html
{% extends 'base/base.html' %}
{% load widget_tweaks %}

{%block titulo-miga%}
<div class="row">
    <div class="col-12">
        <div class="page-title-box">
            <h4 class="page-title">Página de Clientes</h4>
            <div>

                <ol class="breadcrumb m-0">
                    <li class="breadcrumb-item"><a href="{% url 'base:index' %}">Home</a></li>
                    <li class="breadcrumb-item active">Eliminar Cliente</li>
                </ol>

            </div>
        </div>
    </div>
</div>
{% endblock%}

{% block contenido %}


<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body">
                <h4 class="header-title">Eliminar Cliente</h4>
               <hr>
               <div class="alert alert-danger bg-danger text-white border-0" role="alert">
                Esta seguro de  <strong>ELIMINAR</strong> este cliente...???
                <br>
                <br>
                Apellido: <strong> {{object.apellido_cliente}}, {{object.nombre_cliente}}</strong>
                <br>
                <br>
                DNI: <strong>{{object.dni_cliente}}</strong> 
                </div>
                <hr>
                <form method="POST">
                    {% csrf_token %}
                   
                    <button type="submit" class="btn btn-warning waves-effect waves-light">Eliminar Cliente</button>
                    <button onClick="history.go(-1);" class="btn btn-success waves-effect waves-light">Cancelar</button>
                </form>

            </div> 
    </div> 
</div>
</div>
{% endblock %}

app/cliente/templates/cliente/listado_cliente.html
{% extends 'base/base.html' %}

{%block titulo-miga%}
<div class="row">
    <div class="col-12">
        <div class="page-title-box">
            <h4 class="page-title">Página de Clientes</h4>
            <div>

                <ol class="breadcrumb m-0">
                    <li class="breadcrumb-item"><a href="{% url 'base:index' %}">Home</a></li>
                    <li class="breadcrumb-item active">Listado de Cliente</li>
                </ol>

            </div>
        </div>
    </div>
</div>
{% endblock%}

{% block contenido %}

<div class="row">
    <div class="col-lg-12">
        <div class="card">
            <div class="card-body">
                <h4 class="header-title">Listado de Clientes</h4>
                

                <div class="table-responsive">
                    <table class="table table-dark mb-0">
                        <thead>
                            <tr>
                                <th>Apellido</th>
                                <th>Nombre</th>
                                <th>DNI</th>
                                <th>Domicilio</th>
                                <th>Acciones</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for i in cli %}
                            <tr>
                                <th>{{i.apellido_cliente}}</th>
                                <td>{{i.nombre_cliente}}</td>
                                <td>{{i.dni_cliente}}</td>
                                <td>{{i.domicilio_cliente}}</td>
                                <td><a href="{% url 'cliente:detallecliente' i.id %}"" class="btn btn-soft-info btn-rounded waves-effect waves-light">Más Info</a>
                                <a href="{% url 'cliente:editarcliente' i.id %}"" class="btn btn-soft-warning btn-rounded waves-effect waves-light">Editar</a>
                                <a href="{% url 'cliente:eliminarcliente' i.id %}"" class="btn btn-soft-danger btn-rounded waves-effect waves-light">Eliminar</a></td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div> <!-- end card -->
    </div> <!-- end col -->
</div>

{% endblock %}

app/cliente/templates/cliente/nuevo_cliente.html
{% extends 'base/base.html' %}
{% load widget_tweaks %}

{%block titulo-miga%}
<div class="row">
    <div class="col-12">
        <div class="page-title-box">
            <h4 class="page-title">Página de Clientes</h4>
            <div>

                <ol class="breadcrumb m-0">
                    <li class="breadcrumb-item"><a href="{% url 'base:index' %}">Home</a></li>
                    <li class="breadcrumb-item active">Cargar Nuevo Cliente</li>
                </ol>

            </div>
        </div>
    </div>
</div>
{% endblock%}

{% block contenido %}


<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body">
                <h4 class="header-title">Formulario de Carga de Cliente</h4>
               <hr>
                <form method="POST">
                    {% csrf_token %}



                    <div class="row">
                        <div class="col-md-6 mb-3">
                            <label for="inputEmail4" class="form-label">Apellido</label>
                            {% render_field form.apellido_cliente class="form-control" %}
                        </div>
                        <div class="col-md-6 mb-3">
                            <label for="inputPassword4" class="form-label">Nombre</label>
                            {% render_field form.nombre_cliente class="form-control" %}
                        </div>
                    </div>

                    <div class="mb-3">
                        <label for="inputAddress" class="form-label">Domicilio</label>
                        {% render_field form.domicilio_cliente class="form-control" %}
                    </div>

                    <div class="row">
                        <div class="mb-3 col-md-6">
                            <label for="inputCity" class="form-label">DNI</label>
                            {% render_field form.dni_cliente class="form-control" %}
                        </div>
                        <div class="mb-3 col-md-4">
                            <label for="inputState" class="form-label">Tel. Fijo</label>
                            {% render_field form.telfijo_cliente class="form-control" %}
                        </div>
                        <div class="mb-3 col-md-2">
                            <label for="inputZip" class="form-label">Tel. Móvil</label>
                            {% render_field form.movil_cliente class="form-control" %}
                        </div>
                    </div>
                    <div class="row">
                        <div class="mb-3 col-md-6">
                            <label for="inputCity" class="form-label">Email</label>
                            {% render_field form.email_cliente class="form-control" %}
                        </div>
                        <div class="mb-3 col-md-4">
                            <label for="inputState" class="form-label">Código Postal</label>
                            {% render_field form.zipcode_cliente class="form-control" %}
                        </div>
                        <div class="mb-3 col-md-2">
                            <label for="inputZip" class="form-label">País</label>
                            {% render_field form.id_pais class="form-control" %}
                        </div>
                    </div>
                    <button type="submit" class="btn btn-primary waves-effect waves-light">Cargar Registro</button>

                </form>

            </div> 
    </div> 
</div>
</div>
{% endblock %}