app/base/urls.py
from django.urls import path

from app.base.views import Home

#--Importamos las view de la aplicación base
from .views import Home, Acercade

from django.contrib.auth import views as auth_views

#--Generamos las urls de la aplicación base 

urlpatterns = [
    
    # Url de vistas basadas en clase
    path('',Home.as_view(), name='index'),
    path('acercade/', Acercade.as_view(), name='acercade'),

    path('login/',auth_views.LoginView.as_view(template_name='base/login.html'),name='login'),
	path('logout/',auth_views.LogoutView.as_view(template_name='base/login.html'),name='logout'),


    #Url de vistas en funciones
    #path('',Home, name='index'),
    #path('acercade/', Acercade, name='acercade'),
   
]

app/producto/urls.py
from django.urls import path

from .views import NuevoProducto, ListadoProducto, DetalleProducto, BuscarProducto, EditarProducto, EliminarProducto

urlpatterns = [
    # Url de vistas basadas en clase

    path('nuevoproducto/',NuevoProducto.as_view(),name='nuevoproducto'),
    path('listadoproducto/',ListadoProducto.as_view(), name='listadoproducto'),
    path('detalleproducto/<int:pk>',DetalleProducto.as_view(),name='detalleproducto'),
    path('buscarproducto/',BuscarProducto.as_view(),name='buscarproducto'),
    path('editarproducto/<int:pk>',EditarProducto.as_view(),name='editarproducto'),
    path('eliminarproducto/<int:pk>',EliminarProducto.as_view(),name='eliminarproducto')

    # Url de vistas basadas en función
    #path('nuevoproducto/',NuevoProducto,name='nuevoproducto'),
    #path('listadoproducto/', ListadoProducto, name='listadoproducto'),
]

tienda/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include(('app.base.urls','base'),namespace='base')),
    path('producto/',include(('app.producto.urls','producto'),namespace='producto')),
    path('cliente/',include(('app.cliente.urls','cliente'),namespace='cliente')),
    path('vendedor/',include(('app.vendedor.urls','vendedor'),namespace='vendedor')),
    path('proveedor/',include(('app.proveedor.urls','proveedor'),namespace='proveedor')),
    path('usuario/',include(('app.usuario.urls','usuario'),namespace='usuario'))
]

app/producto/models.py
from django.db import models

# Create your models here.
class Categoria(models.Model):

    nombre = models.CharField(max_length=150, verbose_name='Nombre de la Categoría',unique=True,
                blank=False, null=False)
    

    def __str__(self):
        return '{}'.format(self.nombre)
    
    
    class Meta:
        verbose_name_plural = "Categorias"
        ordering = ['nombre']


class Nacionalidad(models.Model):

    nacionalidad = models.CharField(max_length=150, verbose_name='Nacionalidad Producto',unique=True,
                blank=False, null=False)
    

    def __str__(self):
        return '{}'.format(self.nacionalidad)

    
    class Meta:
        verbose_name_plural = "Nacionalidades"
        ordering = ['nacionalidad']



class Marca(models.Model):

    marca = models.CharField(max_length=150, verbose_name='Marca Producto',unique=True,
                blank=False, null=False)
    

    def __str__(self):
        return '{}'.format(self.marca)

    
    class Meta:
        verbose_name_plural = "Marcas"
        ordering = ['marca']




class Producto(models.Model):
    codigo_producto = models.CharField(max_length=10, verbose_name='Código Producto',unique=True)
    nombre_producto = models.CharField(max_length=150, verbose_name='Nombre Producto', unique=True,)
    descripcion_producto = models.TextField(blank=True, null=True, verbose_name='Características') 
    precio_unitario = models.DecimalField(default=0.00, max_digits=9, decimal_places=2,
                    verbose_name='Precio Unitario')
    id_categoria = models.ForeignKey(Categoria, on_delete=models.CASCADE,verbose_name='Categoria Producto')
    id_nacionalidad = models.ForeignKey(Nacionalidad, on_delete=models.CASCADE,verbose_name='Nacionalidad Producto')
    id_marca = models.ForeignKey(Marca, on_delete=models.CASCADE,verbose_name='Marca Producto')
   
    

    def __str__(self):
        return 'Nombre del Producto: {}'.format(self.nombre_producto)
    

    class Meta:
        verbose_name_plural = 'Productos'
        ordering = ['nombre_producto'] 

app/producto/forms.py
from django import forms
from .models import Producto

class ProductoForm(forms.ModelForm):

    class Meta:
        model = Producto
        fields = ('__all__')

app/producto/views.py
from django.shortcuts import render, redirect


from django.urls import reverse_lazy
from django.views import generic

from django.contrib.auth.mixins import LoginRequiredMixin


from .models import Producto
from .forms import ProductoForm

# Vistas Basadas en Clase

class NuevoProducto(LoginRequiredMixin,generic.CreateView):
    model = Producto
    template_name = 'producto/nuevo_producto.html'
    form_class = ProductoForm
    contex_object_name = 'form'
    success_url = reverse_lazy('producto:listadoproducto')
    login_url = 'base:login'


class ListadoProducto(LoginRequiredMixin,generic.ListView):
    model = Producto
    template_name = 'producto/listado_producto.html'
    context_object_name = 'produ'
    login_url = 'base:login'


class DetalleProducto(LoginRequiredMixin,generic.DetailView):
    model = Producto
    template_name = 'producto/detalle_producto.html'
    context_object_name = 'produ'
    login_url = 'base:login'


class BuscarProducto(LoginRequiredMixin,generic.ListView):
    template_name = 'producto/buscar_producto.html'
    context_object_name = 'produ'
    login_url = 'base:login'
    
    def get_queryset(self):
        palabra_clave = self.request.GET.get("kword")
        if not palabra_clave:
            palabra_clave = "None"
        return Producto.objects.filter(nombre_producto__icontains=palabra_clave)



class EditarProducto(LoginRequiredMixin,generic.UpdateView):
    model = Producto
    template_name = 'producto/editar_producto.html'
    context_object_name = 'obj'
    form_class = ProductoForm
    success_url = reverse_lazy('producto:listadoproducto')
    login_url = 'base:login'



class EliminarProducto(LoginRequiredMixin,generic.DeleteView):
    model = Producto
    template_name = 'producto/eliminar_producto.html'
    success_url = reverse_lazy('producto:listadoproducto')
    login_url = 'base:login'


   

"""
#Vistas Basadas en Función

# Vista de Nuevo Producto.
def NuevoProducto(request):

    if request.method == 'POST':
        formulario_producto= ProductoForm(request.POST)
        if formulario_producto.is_valid():
            formulario_producto.save()
            return redirect('producto:listadoproducto')
    else:
        formulario_producto = ProductoForm()
    
    return render(request, 'producto/nuevo_producto.html',{'form':formulario_producto})

   


# Vista Listado Producto
def ListadoProducto(request):
    producto = Producto.objects.all() # Trae todos los registros de la tabla producto
    return render(request, 'producto/listado_producto.html',{'produ':producto})
"""

app/producto/templates/producto/buscar_producto.html
{% extends 'base/base.html' %}
{% load widget_tweaks %}

{%block titulo-miga%}
<div class="row">
    <div class="col-12">
        <div class="page-title-box">
            <h4 class="page-title">Página de Productos</h4>
            <div>

                <ol class="breadcrumb m-0">
                    <li class="breadcrumb-item"><a href="{% url 'base:index' %}">Home</a></li>
                    <li class="breadcrumb-item active">Buscar Producto</li>
                </ol>

            </div>
        </div>
    </div>
</div>
{% endblock%}

{% block contenido %}


<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body">
                <h4 class="header-title">Formulario de Búsqueda de Producto</h4>
                <br>
                <form method="GET">
                    {% csrf_token %}

                    <div class="mb-3">
                        <label for="example-input-normal" class="form-label">Buscar Producto (Nombre)</label>
                        <input type="text" id="kword" name="kword" class="form-control">
                    </div>

                    <button type="submit" class="btn btn-primary waves-effect waves-light">Buscar Producto</button>

                </form>

            </div>
        </div>
    </div>

</div>

<hr>
<div class="row">
    <div class="col-lg-12">
        <div class="card">
            <div class="card-body">
                <h4 class="header-title">Listado de Productos</h4>
                
                {% if produ %}
                <div class="table-responsive">
                    <table class="table table-dark mb-0">
                        <thead>
                            <tr>
                                <th>Código</th>
                                <th>Nombre</th>
                                <th>Marca</th>
                                <th>Categoría</th>
                                <th>Acciones</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for i in produ %}
                            <tr>
                                <th>{{i.codigo_producto}}</th>
                                <td>{{i.nombre_producto}}</td>
                                <td>{{i.id_marca}}</td>
                                <td>{{i.id_categoria}}</td>
                              
                                <td>
                                    <a href="{%url 'producto:detalleproducto' i.id%}" class="btn btn-soft-info btn-rounded waves-effect waves-light">Más Info</a>
                                   
                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
                {% else %}
                <div class="alert alert-warning" role="alert">
                    <i class="mdi mdi-alert-outline me-2"></i> ATENCIÓN: <strong>No se encuentran coincidencias</strong> 
                </div>
                {% endif %}
            </div>
        </div> <!-- end card -->
    </div> <!-- end col -->
</div>



{% endblock %}

app/producto/templates/producto/detalle_producto.html
{% extends 'base/base.html' %}


{%block titulo-miga%}
<div class="row">
    <div class="col-12">
        <div class="page-title-box">
            <h4 class="page-title">Página de Productos</h4>
            <div>

                <ol class="breadcrumb m-0">
                    <li class="breadcrumb-item"><a href="{% url 'base:index' %}">Home</a></li>
                    <li class="breadcrumb-item active">Detalle del producto</li>
                </ol>

            </div>
        </div>
    </div>
</div>
{% endblock%}

{% block contenido %}


<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body">
                <h4 class="header-title">Detalles del Producto</h4>
               <hr>

                <form>
                    <div class="row">
                        <div class="mb-3 col-md-4">
                            <label for="inputEmail4" class="form-label">Nombre</label>
                            <input type="text" class="form-control" value="{{produ.nombre_producto}}" >
                        </div>
                        <div class="mb-3 col-md-4">
                            <label for="inputPassword4" class="form-label">Código</label>
                            <input type="text" class="form-control" value="{{produ.codigo_producto}}" >
                        </div>
                        <div class="mb-3 col-md-4">
                            <label for="inputState" class="form-label">Marca</label>
                            <input type="text" class="form-control" value="{{produ.id_marca}}">
                        </div>
                    </div>

                    <div class="mb-3">
                        <label for="inputAddress" class="form-label">Descripción</label>
                       
                        <textarea class="form-control"  id="example-textarea" rows="5">{{produ.descripcion_producto}}</textarea>
                    </div>

                    <div class="row">
                        <div class="mb-3 col-md-4">
                            <label for="inputCity" class="form-label">Precio Unitario</label>
                            <input type="text" class="form-control" value="$ {{produ.precio_unitario}}">
                        </div>
                        <div class="mb-3 col-md-4">
                            <label for="inputState" class="form-label">Categoría</label>
                            <input type="text" class="form-control" value="{{produ.id_categoria}}">
                        </div>
                        <div class="mb-3 col-md-4">
                            <label for="inputState" class="form-label">Nacionalidad</label>
                            <input type="text" class="form-control" value="{{produ.id_nacionalidad}}">
                        </div>
                        
                    </div>

                   
                </form>
                <button onclick="history.go(-1)" class="btn btn-success waves-effect waves-light">Regresar</button>
            </div> <!-- end card-body -->
        </div> <!-- end card-->
    </div> <!-- end col -->
</div>
{% endblock %}

app/producto/templates/producto/editar_producto.html
{% extends 'base/base.html' %}
{% load widget_tweaks %}

{%block titulo-miga%}
<div class="row">
    <div class="col-12">
        <div class="page-title-box">
            <h4 class="page-title">Página de Productos</h4>
            <div>

                <ol class="breadcrumb m-0">
                    <li class="breadcrumb-item"><a href="{% url 'base:index' %}">Home</a></li>
                    <li class="breadcrumb-item active">Editar Datos Producto</li>
                </ol>

            </div>
        </div>
    </div>
</div>
{% endblock%}

{% block contenido %}


<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body">
                <h4 class="header-title">Formulario de Edición de Producto</h4>
               <hr>
                <form method="POST">
                    {% csrf_token %}
                    <div class="row">
                        <div class="col-md-6 mb-3">
                            <label for="inputEmail4" class="form-label">Código</label>
                            {% render_field form.codigo_producto class="form-control" %}
                        </div>
                        <div class="col-md-6 mb-3">
                            <label for="inputPassword4" class="form-label">Nombre</label>
                            {% render_field form.nombre_producto class="form-control" %}
                        </div>
                        <div class="mb-3">
                            <label for="inputAddress" class="form-label">Descripcion</label>
                            {% render_field form.descripcion_producto class="form-control" %}
                        </div>
                    </div>

                    <div class="row">
                        <div class="mb-3 col-md-6">
                            <label for="inputCity" class="form-label">Precio Unitario</label>
                            {% render_field form.precio_unitario class="form-control" %}
                        </div>
                        <div class="mb-3 col-md-4">
                            <label for="inputState" class="form-label">Categoría</label>
                            {% render_field form.id_categoria class="form-control" %}
                        </div>
                        <div class="mb-3 col-md-2">
                            <label for="inputZip" class="form-label">Nacionalidad</label>
                            {% render_field form.id_nacionalidad class="form-control" %}
                        </div>
                        <div class="mb-3 col-md-2">
                            <label for="inputZip" class="form-label">Marca</label>
                            {% render_field form.id_marca class="form-control" %}
                        </div>
                       
                    </div>
                    <button type="submit" class="btn btn-primary waves-effect waves-light">Editar Registro</button>
                    <button onClick="history.go(-1);" class="btn btn-success waves-effect waves-light">Cancelar</button>
                </form>

            </div> 
    </div> 
</div>
</div>
{% endblock %}

app/producto/templates/producto/eliminar_producto.html
{% extends 'base/base.html' %}
{% load widget_tweaks %}

{%block titulo-miga%}
<div class="row">
    <div class="col-12">
        <div class="page-title-box">
            <h4 class="page-title">Página de Productos</h4>
            <div>

                <ol class="breadcrumb m-0">
                    <li class="breadcrumb-item"><a href="{% url 'base:index' %}">Home</a></li>
                    <li class="breadcrumb-item active">Eliminar Producto</li>
                </ol>

            </div>
        </div>
    </div>
</div>
{% endblock%}

{% block contenido %}


<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body">
                <h4 class="header-title">Eliminar Producto</h4>
               <hr>
               <div class="alert alert-danger bg-danger text-white border-0" role="alert">
                Esta seguro de  <strong>ELIMINAR</strong> este producto...???
                <br>
                <br>
                Código / Nombre: <strong> {{object.codigo_producto}}, {{object.nombre_producto}}</strong>
                <br>
                <br>
                Marca: <strong>{{object.id_marca}}</strong> 
                </div>
                <hr>
                <form method="POST">
                    {% csrf_token %}
                   
                    <button type="submit" class="btn btn-warning waves-effect waves-light">Eliminar Producto</button>
                    <button onClick="history.go(-1);" class="btn btn-success waves-effect waves-light">Cancelar</button>
                </form>

            </div> 
    </div> 
</div>
</div>
{% endblock %}

app/producto/templates/producto/listado_producto.html
{% extends 'base/base.html' %}

{%block titulo-miga%}
<div class="row">
    <div class="col-12">
        <div class="page-title-box">
            <h4 class="page-title">Página de Productos</h4>
            <div>

                <ol class="breadcrumb m-0">
                    <li class="breadcrumb-item"><a href="{% url 'base:index' %}">Home</a></li>
                    <li class="breadcrumb-item active">Listado de Productos</li>
                </ol>

            </div>
        </div>
    </div>
</div>
{% endblock%}

{% block contenido %}
<div class="row">
    <div class="col-lg-12">
        <div class="card">
            <div class="card-body">
                <h4 class="header-title">Listado de Productos</h4>
                

                <div class="table-responsive">
                    <table class="table table-dark mb-0">
                        <thead>
                            <tr>
                                <th>Código</th>
                                <th>Nombre</th>
                                <th>Marca</th>
                                <th>Categoría</th>
                                <th>Acciones</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for i in produ %}
                            <tr>
                                <th>{{i.codigo_producto}}</th>
                                <td>{{i.nombre_producto}}</td>
                                <td>{{i.id_marca}}</td>
                                <td>{{i.id_categoria}}</td>
                              
                                <td>
                                    <a href="{%url 'producto:detalleproducto' i.id%}" class="btn btn-soft-info btn-rounded waves-effect waves-light">Más Info</a>
                                    <a href="{%url 'producto:editarproducto' i.id%}" class="btn btn-soft-warning btn-rounded waves-effect waves-light">Editar</a>
                                    <a href="{%url 'producto:eliminarproducto' i.id%}" class="btn btn-soft-danger btn-rounded waves-effect waves-light">Eliminar</a>
                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div> <!-- end card -->
    </div> <!-- end col -->
</div>

{% endblock %}

app/producto/templates/producto/nuevo_producto.html
{% extends 'base/base.html' %}
{% load widget_tweaks %}

{%block titulo-miga%}
<div class="row">
    <div class="col-12">
        <div class="page-title-box">
            <h4 class="page-title">Página de Productos</h4>
            <div>

                <ol class="breadcrumb m-0">
                    <li class="breadcrumb-item"><a href="{% url 'base:index' %}">Home</a></li>
                    <li class="breadcrumb-item active">Cargar Nuevo Porducto</li>
                </ol>

            </div>
        </div>
    </div>
</div>
{% endblock%}

{% block contenido %}

<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body">
                <h4 class="header-title">Formulario de Carga de Producto</h4>
               <hr>
                <form method="POST">
                    {% csrf_token %}
                    <div class="row">
                        <div class="col-md-6 mb-3">
                            <label for="inputEmail4" class="form-label">Código</label>
                            {% render_field form.codigo_producto class="form-control" %}
                        </div>
                        <div class="col-md-6 mb-3">
                            <label for="inputPassword4" class="form-label">Nombre</label>
                            {% render_field form.nombre_producto class="form-control" %}
                        </div>
                        <div class="mb-3">
                            <label for="inputAddress" class="form-label">Descripcion</label>
                            {% render_field form.descripcion_producto class="form-control" %}
                        </div>
                    </div>

                    

                    <div class="row">
                        <div class="mb-3 col-md-6">
                            <label for="inputCity" class="form-label">Precio Unitario</label>
                            {% render_field form.precio_unitario class="form-control" %}
                        </div>
                        <div class="mb-3 col-md-4">
                            <label for="inputState" class="form-label">Categoría</label>
                            {% render_field form.id_categoria class="form-control" %}
                        </div>
                        <div class="mb-3 col-md-2">
                            <label for="inputZip" class="form-label">Nacionalidad</label>
                            {% render_field form.id_nacionalidad class="form-control" %}
                        </div>
                        <div class="mb-3 col-md-2">
                            <label for="inputZip" class="form-label">Marca</label>
                            {% render_field form.id_marca class="form-control" %}
                        </div>
                       
                    </div>
                   
                    <button type="submit" class="btn btn-primary waves-effect waves-light">Cargar Registro</button>

                </form>

            </div> 
    </div> 
</div>
</div>


{% endblock %}