app/base/urls.py
from django.urls import path

from app.base.views import Home

#--Importamos las view de la aplicación base
from .views import Home, Acercade

from django.contrib.auth import views as auth_views

#--Generamos las urls de la aplicación base 

urlpatterns = [
    
    # Url de vistas basadas en clase
    path('',Home.as_view(), name='index'),
    path('acercade/', Acercade.as_view(), name='acercade'),

    path('login/',auth_views.LoginView.as_view(template_name='base/login.html'),name='login'),
	path('logout/',auth_views.LogoutView.as_view(template_name='base/login.html'),name='logout'),


    #Url de vistas en funciones
    #path('',Home, name='index'),
    #path('acercade/', Acercade, name='acercade'),
   
]

app/vendedor/urls.py
from django.urls import path

from .views import NuevoVendedor, ListadoVendedor,DetalleVendedor, BuscarVendedor, EditarVendedor, EliminarVendedor

urlpatterns = [
    path('nuevovendedor/',NuevoVendedor.as_view(), name='nuevovendedor'),
    path('listadovendedor/',ListadoVendedor.as_view(),name='listadovendedor'),
    path('detallevendedor/<int:pk>',DetalleVendedor.as_view(),name='detallevendedor'),
    path('buscarvendedor/',BuscarVendedor.as_view(),name='buscarvendedor'),
    path('editarvendedor/<int:pk>',EditarVendedor.as_view(),name='editarvendedor'),
    path('eliminarvendedor/<int:pk>',EliminarVendedor.as_view(),name='eliminarvendedor')

    # Urls de vistas basadas en función
    #path('nuevovendedor/',NuevoVendedor, name='nuevovendedor'),
    #path('listadovendedor/',ListadoVendedor,name='listadovendedor'),
]

tienda/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include(('app.base.urls','base'),namespace='base')),
    path('producto/',include(('app.producto.urls','producto'),namespace='producto')),
    path('cliente/',include(('app.cliente.urls','cliente'),namespace='cliente')),
    path('vendedor/',include(('app.vendedor.urls','vendedor'),namespace='vendedor')),
    path('proveedor/',include(('app.proveedor.urls','proveedor'),namespace='proveedor')),
    path('usuario/',include(('app.usuario.urls','usuario'),namespace='usuario'))
]

app/vendedor/models.py
from django.db import models

# Create your models here.
SUCURSAL =(
    ('0', 'Seleccionar Sucursal'),
    ('1', 'Casa Central'),
    ('2', 'Sucursal Centro 1'),
    ('3', 'Sucursal Centro 2'),
    ('4', 'Sucursal Oeste 1'),
    ('5', 'Sucursal Sur 1'),


    )


class Vendedor(models.Model):
    nombre_vendedor = models.CharField(max_length=50, verbose_name='Nombre')
    apellido_vendedor = models.CharField(max_length=50, verbose_name='Apellido')
    dni_vendedor = models.CharField(max_length=10, verbose_name='DNI') 
    domicilio_vendedor = models.CharField(max_length=150, verbose_name='Domicilio')
    codigo_vendedor = models.CharField(max_length=10, verbose_name='Código',null=True, blank=True)
    sucursal = models.CharField(max_length=1,verbose_name='Sucursal',choices=SUCURSAL, default='0')
    
   
    

    def __str__(self):
        return 'Apellido y Nombre: {}, {}'.format(self.apellido_vendedor,self.nombre_vendedor)
    
   
    class Meta:
        verbose_name_plural = 'Vendedores'
        ordering = ['apellido_vendedor'] 

app/vendedor/forms.py
from django import forms
from .models import Vendedor

class VendedorForm(forms.ModelForm):

    class Meta:
        model = Vendedor
        fields = ('__all__')
    

app/vendedor/views.py
from django.shortcuts import render, redirect

from django.urls import reverse_lazy
from django.views import generic

from django.contrib.auth.mixins import LoginRequiredMixin

from .models import Vendedor
from .forms import VendedorForm


# Vistas Basadas en Clase
class NuevoVendedor(LoginRequiredMixin,generic.CreateView):
    model = Vendedor
    template_name = 'vendedor/nuevo_vendedor.html'
    context_object_name = 'form'
    form_class = VendedorForm
    succes_url = reverse_lazy('vendedor:listadovendedor')
    login_url = 'base:login'


class ListadoVendedor(LoginRequiredMixin,generic.ListView):
    model = Vendedor
    template_name = 'vendedor/listado_vendedor.html'
    context_object_name = 'vend'
    login_url = 'base:login'


class DetalleVendedor(LoginRequiredMixin,generic.DetailView):
    model = Vendedor
    template_name = 'vendedor/detalle_vendedor.html'
    context_object_name = 'vend'
    login_url = 'base:login'


class BuscarVendedor(LoginRequiredMixin,generic.ListView):
    template_name = 'vendedor/buscar_vendedor.html'
    context_object_name = 'vend'
    login_url = 'base:login'
    
    def get_queryset(self):
        palabra_clave = self.request.GET.get("kword")
        if not palabra_clave:
            palabra_clave = "None"
        return Vendedor.objects.filter(apellido_vendedor__icontains=palabra_clave)



class EditarVendedor(LoginRequiredMixin,generic.UpdateView):
    model = Vendedor
    template_name = 'vendedor/editar_vendedor.html'
    context_object_name = 'obj'
    form_class = VendedorForm
    success_url = reverse_lazy('vendedor:listadovendedor')
    login_url = 'base:login'



class EliminarVendedor(LoginRequiredMixin,generic.DeleteView):
    model = Vendedor
    template_name = 'vendedor/eliminar_vendedor.html'
    success_url = reverse_lazy('vendedor:listadovendedor')
    login_url = 'base:login'



"""
VISTAS BASADAS EN FUNCION

# Vista de Nuevo Vendedor.
def NuevoVendedor(request):

    if request.method == 'POST':
        formulario_vendedor= VendedorForm(request.POST)
        if formulario_vendedor.is_valid():
            formulario_vendedor.save()
            return redirect('vendedor:listadovendedor')
    else:
        formulario_vendedor = VendedorForm()
    
    return render(request, 'vendedor/nuevo_vendedor.html',{'form':formulario_vendedor})

   


# Vista Listado Vendedor
def ListadoVendedor(request):
    vendedor = Vendedor.objects.all() # Trae todos los registros de la tabla vendedor
    return render(request, 'vendedor/listado_vendedor.html',{'vend':vendedor})
"""

app/vendedor/templates/vendedor/buscar_vendedor.html
{% extends 'base/base.html' %}
{% load widget_tweaks %}

{%block titulo-miga%}
<div class="row">
    <div class="col-12">
        <div class="page-title-box">
            <h4 class="page-title">Página de Vendedores</h4>
            <div>

                <ol class="breadcrumb m-0">
                    <li class="breadcrumb-item"><a href="{% url 'base:index' %}">Home</a></li>
                    <li class="breadcrumb-item active">Buscar Vendedor</li>
                </ol>

            </div>
        </div>
    </div>
</div>
{% endblock%}

{% block contenido %}


<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body">
                <h4 class="header-title">Formulario de Búsqueda de Vendedores</h4>
                <br>
                <form method="GET">
                    {% csrf_token %}

                    <div class="mb-3">
                        <label for="example-input-normal" class="form-label">Buscar Vendedor (Apellido)</label>
                        <input type="text" id="kword" name="kword" class="form-control">
                    </div>

                    <button type="submit" class="btn btn-primary waves-effect waves-light">Buscar Vendedor</button>

                </form>

            </div>
        </div>
    </div>

</div>

<hr>
<div class="row">
    <div class="col-lg-12">
        <div class="card">
            <div class="card-body">
                <h4 class="header-title">Listado de Vendedores</h4>
                <hr>
                {% if vend %}
                <div class="table-responsive">
                    <table class="table table-dark mb-0">
                        <thead>
                            <tr>
                                <th>Apellido</th>
                                <th>Nombre</th>
                                <th>DNI</th>
                                <th>Código Vendedor</th>
                                <th>Sucursal</th>
                                <th>Acciones</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for i in vend %}
                            <tr>
                                <th>{{i.apellido_vendedor}}</th>
                                <td>{{i.nombre_vendedor}}</td>
                                <td>{{i.dni_vendedor}}</td>
                                <td>{{i.codigo_vendedor}}</td>
                                <td>{{i.sucursal}}</td>
                              
                                <td>
                                    <a href="{%url 'vendedor:detallevendedor' i.id%}" class="btn btn-soft-info btn-rounded waves-effect waves-light">Más Info</a>
                                </td>
                                   
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
                {% else %}
                <div class="alert alert-warning" role="alert">
                    <i class="mdi mdi-alert-outline me-2"></i> ATENCIÓN: <strong>No se encuentran coincidencias</strong> 
                </div>
                {% endif %}
            </div>
        </div> <!-- end card -->
    </div> <!-- end col -->
</div>




{% endblock %}

app/vendedor/templates/vendedor/detalle_vendedor.html
{% extends 'base/base.html' %}


{%block titulo-miga%}
<div class="row">
    <div class="col-12">
        <div class="page-title-box">
            <h4 class="page-title">Página de vendedors</h4>
            <div>

                <ol class="breadcrumb m-0">
                    <li class="breadcrumb-item"><a href="{% url 'base:index' %}">Home</a></li>
                    <li class="breadcrumb-item active">Detalle del vendedor</li>
                </ol>

            </div>
        </div>
    </div>
</div>
{% endblock%}

{% block contenido %}


<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body">
                <h4 class="header-title">Detalles del Vendedor</h4>
               <hr>

                <form>
                    <div class="row">
                        <div class="col-md-6 mb-3">
                            <label for="inputEmail4" class="form-label">Apellido</label>
                            <input type="text" class="form-control" value="{{vend.apellido_vendedor}}" placeholder="Email">
                        </div>
                        <div class="col-md-6 mb-3">
                            <label for="inputPassword4" class="form-label">Nombre</label>
                            <input type="text" class="form-control" value="{{vend.nombre_vendedor}}" placeholder="Password">
                        </div>
                    </div>

                    <div class="mb-3">
                        <label for="inputAddress" class="form-label">Domicilio</label>
                        <input type="text" class="form-control" value="{{vend.domicilio_vendedor}}" placeholder="1234 Main St">
                    </div>

                    <div class="row">
                        <div class="mb-3 col-md-4">
                            <label for="inputCity" class="form-label">DNI</label>
                            <input type="text" class="form-control" value="{{vend.dni_vendedor}}">
                        </div>
                        <div class="mb-3 col-md-4">
                            <label for="inputState" class="form-label">Código</label>
                            <input type="text" class="form-control" value="{{vend.codigo_vendedor}}">
                        </div>
                        <div class="mb-3 col-md-4">
                            <label for="inputState" class="form-label">Sucursal</label>
                            <input type="text" class="form-control" value="{{vend.sucursal}}">
                        </div>
                        
                    </div>

                   
                </form>
                <button onclick="history.go(-1)" class="btn btn-success waves-effect waves-light">Regresar</button>
            </div> <!-- end card-body -->
        </div> <!-- end card-->
    </div> <!-- end col -->
</div>
{% endblock %}

app/vendedor/templates/vendedor/editar_vendedor.html
{% extends 'base/base.html' %}
{% load widget_tweaks %}

{%block titulo-miga%}
<div class="row">
    <div class="col-12">
        <div class="page-title-box">
            <h4 class="page-title">Página de Vendedores</h4>
            <div>

                <ol class="breadcrumb m-0">
                    <li class="breadcrumb-item"><a href="{% url 'base:index' %}">Home</a></li>
                    <li class="breadcrumb-item active">Editar Datos Vendedor</li>
                </ol>

            </div>
        </div>
    </div>
</div>
{% endblock%}

{% block contenido %}


<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body">
                <h4 class="header-title">Formulario de Edición de Vendedores</h4>
               <hr>
                <form method="POST">
                    {% csrf_token %}
                    <div class="row">
                        <div class="col-md-6 mb-3">
                            <label for="inputEmail4" class="form-label">Apellido</label>
                            {% render_field form.apellido_vendedor class="form-control" %}
                        </div>
                        <div class="col-md-6 mb-3">
                            <label for="inputPassword4" class="form-label">Nombre</label>
                            {% render_field form.nombre_vendedor class="form-control" %}
                        </div>
                    </div>

                    <div class="mb-3">
                        <label for="inputAddress" class="form-label">Domicilio</label>
                        {% render_field form.domicilio_vendedor class="form-control" %}
                    </div>

                    <div class="row">
                        <div class="mb-3 col-md-6">
                            <label for="inputCity" class="form-label">DNI</label>
                            {% render_field form.dni_vendedor class="form-control" %}
                        </div>
                        <div class="mb-3 col-md-4">
                            <label for="inputState" class="form-label">Código</label>
                            {% render_field form.codigo_vendedor class="form-control" %}
                        </div>
                        <div class="mb-3 col-md-2">
                            <label for="inputZip" class="form-label">Sucursal</label>
                            {% render_field form.sucursal class="form-control" %}
                        </div>
                    </div>
                    
                    <button type="submit" class="btn btn-primary waves-effect waves-light">Editar Registro</button>
                    <button onClick="history.go(-1);" class="btn btn-success waves-effect waves-light">Cancelar</button>
                </form>

            </div> 
    </div> 
</div>
</div>
{% endblock %}

app/vendedor/templates/vendedor/eliminar_vendedor.html
{% extends 'base/base.html' %}
{% load widget_tweaks %}

{%block titulo-miga%}
<div class="row">
    <div class="col-12">
        <div class="page-title-box">
            <h4 class="page-title">Página de Vendedores</h4>
            <div>

                <ol class="breadcrumb m-0">
                    <li class="breadcrumb-item"><a href="{% url 'base:index' %}">Home</a></li>
                    <li class="breadcrumb-item active">Eliminar Vendedor</li>
                </ol>

            </div>
        </div>
    </div>
</div>
{% endblock%}

{% block contenido %}


<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body">
                <h4 class="header-title">Eliminar Vendedor</h4>
               <hr>
               <div class="alert alert-danger bg-danger text-white border-0" role="alert">
                Esta seguro de  <strong>ELIMINAR</strong> este vendedor...???
                <br>
                <br>
                Apellido: <strong> {{object.apellido_vendedor}}, {{object.nombre_vendedor}}</strong>
                <br>
                <br>
                DNI: <strong>{{object.dni_vendedor}}</strong> 
                </div>
                <hr>
                <form method="POST">
                    {% csrf_token %}
                   
                    <button type="submit" class="btn btn-warning waves-effect waves-light">Eliminar Vendedor</button>
                    <button onClick="history.go(-1);" class="btn btn-success waves-effect waves-light">Cancelar</button>
                </form>

            </div> 
    </div> 
</div>
</div>
{% endblock %}

app/vendedor/templates/vendedor/listado_vendedor.html
{% extends 'base/base.html' %}

{%block titulo-miga%}
<div class="row">
    <div class="col-12">
        <div class="page-title-box">
            <h4 class="page-title">Página de Vendedores</h4>
            <div>

                <ol class="breadcrumb m-0">
                    <li class="breadcrumb-item"><a href="{% url 'base:index' %}">Home</a></li>
                    <li class="breadcrumb-item active">Listado de Vendedores</li>
                </ol>

            </div>
        </div>
    </div>
</div>
{% endblock%}

{% block contenido %}
<div class="row">
    <div class="col-lg-12">
        <div class="card">
            <div class="card-body">
                <h4 class="header-title">Listado de Vendedores</h4>
                

                <div class="table-responsive">
                    <table class="table table-dark mb-0">
                        <thead>
                            <tr>
                                <th>Apellido</th>
                                <th>Nombre</th>
                                <th>DNI</th>
                                <th>Código Vendedor</th>
                                <th>Sucursal</th>
                                <th>Acciones</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for i in vend %}
                            <tr>
                                <th>{{i.apellido_vendedor}}</th>
                                <td>{{i.nombre_vendedor}}</td>
                                <td>{{i.dni_vendedor}}</td>
                                <td>{{i.codigo_vendedor}}</td>
                                <td>{{i.sucursal}}</td>
                              
                                <td><a href="{%url 'vendedor:detallevendedor' i.id%}" class="btn btn-soft-info btn-rounded waves-effect waves-light">Más Info</a>
                                    <a href="{%url 'vendedor:editarvendedor' i.id%}" class="btn btn-soft-warning btn-rounded waves-effect waves-light">Editar</a>
                                    <a href="{%url 'vendedor:eliminarvendedor' i.id%}" class="btn btn-soft-danger btn-rounded waves-effect waves-light">Eliminar</a></td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div> <!-- end card -->
    </div> <!-- end col -->
</div>
{% endblock %}

app/vendedor/templates/vendedor/nuevo_vendedor.html
{% extends 'base/base.html' %}
{% load widget_tweaks %}

{%block titulo-miga%}
<div class="row">
    <div class="col-12">
        <div class="page-title-box">
            <h4 class="page-title">Página de Vendedores</h4>
            <div>

                <ol class="breadcrumb m-0">
                    <li class="breadcrumb-item"><a href="{% url 'base:index' %}">Home</a></li>
                    <li class="breadcrumb-item active">Cargar Nuevo Vendedor</li>
                </ol>

            </div>
        </div>
    </div>
</div>
{% endblock%}

{% block contenido %}

<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body">
                <h4 class="header-title">Formulario de Carga de Vendedor</h4>
               <hr>
                <form method="POST">
                    {% csrf_token %}
                    <div class="row">
                        <div class="col-md-6 mb-3">
                            <label for="inputEmail4" class="form-label">Apellido</label>
                            {% render_field form.apellido_vendedor class="form-control" %}
                        </div>
                        <div class="col-md-6 mb-3">
                            <label for="inputPassword4" class="form-label">Nombre</label>
                            {% render_field form.nombre_vendedor class="form-control" %}
                        </div>
                        <div class="mb-3">
                            <label for="inputAddress" class="form-label">Domicilio</label>
                            {% render_field form.domicilio_vendedor class="form-control" %}
                        </div>
                    </div>

                    

                    <div class="row">
                        <div class="mb-3 col-md-6">
                            <label for="inputCity" class="form-label">DNI</label>
                            {% render_field form.dni_vendedor class="form-control" %}
                        </div>
                        <div class="mb-3 col-md-4">
                            <label for="inputState" class="form-label">Código</label>
                            {% render_field form.codigo_vendedor class="form-control" %}
                        </div>
                        <div class="mb-3 col-md-2">
                            <label for="inputZip" class="form-label">Sucursal</label>
                            {% render_field form.sucursal class="form-control" %}
                        </div>
                       
                    </div>
                   
                    <button type="submit" class="btn btn-primary waves-effect waves-light">Cargar Registro</button>

                </form>

            </div> 
    </div> 
</div>
</div>

{% endblock %}